Fix some client returns invalid get_many response
Some client's get_many method, e.g pymemcache,
returns like `{'key': False}`.

This cause following TypeError.

```
timestamp, result = data.pop(cache_key)
TypeError: 'bool' object is not iterable
```

This commit check `result` is valid and if invalid value were returned,
ignore and return query result.